
obj-m$(CONFIG_LTO_MENU) := shournalk.o

CFLAGS_MODULE += "-DSHOURNAL_VERSION=\"${shournal_version}\""


ifeq (${shournal_cmake_build}, true)
	common_prefix := ../src/common/
else
    EXTRA_CFLAGS=-O3
endif

shournalk-y += shournalk_main.o event_handler.o shournalk_sysfs.o \
			tracepoint_helper.o event_target.o kutil.o event_queue.o \
			event_consumer.o shournal_kio.o xxhash_shournalk.o \
			kpathtree.o shournalk_test.o shournalk_global.o \
			hash_table_str.o kfileextensions.o \
			event_consumer_cache.o \
                        ${common_prefix}xxhash_common.o \

ifneq (${shournal_cmake_build}, true)
# dkms build

KVER		?= $(shell uname -r)
KBASE		?= /lib/modules/$(KVER)
KBUILD_DIR	?= $(KBASE)/build
MDEST_DIR	?= $(KBASE)/kernel

PWD  := $(shell pwd)

all:
	@$(MAKE) -C $(KBUILD_DIR) M=$(PWD) modules

install:
	install -D -m 755 shournalk.ko $(MDEST_DIR)

endif


clean:
	@rm -rf *~ *.o *.mod *.mod.c .*.cmd .tmp_versions

